const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    // const config_h = b.addConfigHeader(.{ .path = "config.h.in" }, .autoconf, .{
    //     .MAGICKCORE_FILTER_DIRNAME = "filters",
    // });
    const lib = b.addStaticLibrary("MagickWand", null);
    lib.setTarget(target);
    lib.setBuildMode(mode);
    lib.linkLibC();
    // lib.addConfigHeader(config_h);
    lib.addIncludePath(".");
    lib.addIncludePath("MagickCore");
    lib.addIncludePath("MagickWand");
    lib.addCSourceFiles(&.{
        "MagickCore/accelerate.c",
        "MagickCore/animate.c",
        "MagickCore/annotate.c",
        "MagickCore/artifact.c",
        "MagickCore/attribute.c",
        "MagickCore/blob.c",
        "MagickCore/cache-view.c",
        "MagickCore/cache.c",
        "MagickCore/channel.c",
        "MagickCore/cipher.c",
        "MagickCore/client.c",
        "MagickCore/coder.c",
        "MagickCore/color.c",
        "MagickCore/colormap.c",
        "MagickCore/colorspace.c",
        "MagickCore/compare.c",
        "MagickCore/composite.c",
        "MagickCore/compress.c",
        "MagickCore/configure.c",
        "MagickCore/constitute.c",
        "MagickCore/decorate.c",
        "MagickCore/delegate.c",
        "MagickCore/deprecate.c",
        "MagickCore/display.c",
        "MagickCore/distort.c",
        "MagickCore/distribute-cache.c",
        "MagickCore/draw.c",
        "MagickCore/effect.c",
        "MagickCore/enhance.c",
        "MagickCore/exception.c",
        "MagickCore/feature.c",
        "MagickCore/fourier.c",
        "MagickCore/fx.c",
        "MagickCore/gem.c",
        "MagickCore/geometry.c",
        "MagickCore/histogram.c",
        "MagickCore/identify.c",
        "MagickCore/image-view.c",
        "MagickCore/image.c",
        "MagickCore/layer.c",
        "MagickCore/linked-list.c",
        "MagickCore/list.c",
        "MagickCore/locale.c",
        "MagickCore/log.c",
        "MagickCore/magic.c",
        "MagickCore/magick.c",
        "MagickCore/matrix.c",
        "MagickCore/memory.c",
        "MagickCore/mime.c",
        "MagickCore/module.c",
        "MagickCore/monitor.c",
        "MagickCore/montage.c",
        "MagickCore/morphology.c",
        "MagickCore/nt-base.c",
        "MagickCore/nt-feature.c",
        "MagickCore/opencl.c",
        "MagickCore/option.c",
        "MagickCore/paint.c",
        "MagickCore/pixel.c",
        "MagickCore/policy.c",
        "MagickCore/prepress.c",
        "MagickCore/profile.c",
        "MagickCore/property.c",
        "MagickCore/quantize.c",
        "MagickCore/quantum-export.c",
        "MagickCore/quantum-import.c",
        "MagickCore/quantum.c",
        "MagickCore/random.c",
        "MagickCore/registry.c",
        "MagickCore/resample.c",
        "MagickCore/resize.c",
        "MagickCore/resource.c",
        "MagickCore/segment.c",
        "MagickCore/semaphore.c",
        "MagickCore/shear.c",
        "MagickCore/signature.c",
        "MagickCore/splay-tree.c",
        "MagickCore/static.c",
        "MagickCore/statistic.c",
        "MagickCore/stream.c",
        "MagickCore/string.c",
        "MagickCore/thread.c",
        "MagickCore/threshold.c",
        "MagickCore/timer.c",
        "MagickCore/token.c",
        "MagickCore/transform.c",
        "MagickCore/type.c",
        "MagickCore/utility.c",
        "MagickCore/version.c",
        "MagickCore/vision.c",
        "MagickCore/visual-effects.c",
        "MagickCore/vms.c",
        "MagickCore/widget.c",
        "MagickCore/xml-tree.c",
        "MagickCore/xwindow.c",
        "MagickWand/animate.c",
        "MagickWand/compare.c",
        "MagickWand/composite.c",
        "MagickWand/conjure.c",
        "MagickWand/convert.c",
        "MagickWand/deprecate.c",
        "MagickWand/display.c",
        "MagickWand/drawing-wand.c",
        "MagickWand/identify.c",
        "MagickWand/import.c",
        "MagickWand/magick-cli.c",
        "MagickWand/magick-image.c",
        "MagickWand/magick-property.c",
        "MagickWand/magick-wand.c",
        "MagickWand/mogrify.c",
        "MagickWand/montage.c",
        "MagickWand/operation.c",
        "MagickWand/pixel-iterator.c",
        "MagickWand/pixel-wand.c",
        "MagickWand/script-token.c",
        "MagickWand/stream.c",
        "MagickWand/wand-view.c",
        "MagickWand/wand.c",
        "MagickWand/wandcli.c",
    }, &.{});
    lib.install();

    // Needs commit 37424fd (Zig 0.10 + 1329 commits)
    // 1329 was broken though. 1350 (bbab4beda) seems to work
    // NOTE: Would much rather have an "include extensions" option here
    // than playing whack-a-mole
    lib.installHeadersDirectoryOptions(.{
        .source_dir = "MagickCore",
        .install_dir = .header,
        .install_subdir = "MagickCore",
        .exclude_extensions = &.{
            ".c",
            ".in",
            ".h_vms",
            ".1",
            ".com",
            ".map",
            ".am",
        },
    });
    lib.installHeadersDirectory("MagickWand", "MagickWand");
}
